### ISSUE TITLE
Resizing does not update the view

### ISSUE THREAD

**Issue by Hardy7cc** [arijit79/minus#1]
Hi,
this is already really nice.

However I recognized, that when I start with a small window and enlarge this, the view/output does not get updated.

Hardy

**Comment by joyously** [comment]
Wouldn't that be the same regardless of the method of paging?

**Comment by arijit79** [comment]
Thanks for the issue. There is a event emitted when there is a terminal resizing. We can redraw the output once resizing is complete

**Comment by arijit79** [comment]
I have fixed it. You can get it from the latest patch
