### ISSUE TITLE
Remove . vscode

### ISSUE THREAD

**Issue by arijit79** [arijit79/minus#10]
@danieleades in a recent commit, you have pushed your . vscode folder. Could you please remove it, and maybe add it in the . gitignore so that others don't repeat the same mistake

**Comment by danieleades** [comment]
ah apologies. you might have to remove that yourself, as I won't have permission to rebase `main` (i think it's best you amend the previous commit, rather than creating a new one)

**Comment by arijit79** [comment]
These things happen to everyone, so no apologize. Just file a PR with changes I suggested

**Comment by arijit79** [comment]
cadd502 fixes this. Closing
