### ISSUE TITLE
Smol support

### ISSUE THREAD

**Issue by zethra** [arijit79/minus#19]
I'd like to add support for the smol runtime. I'm opening this issue to make sure you wouldn't have an objection to this feature before I go the trouble of implementing it. Thanks.

**Comment by arijit79** [comment]
Thanks for opening up the issue. It wouldn't be that difficult to implement a `smol` runtime function. But again, it would probably be hated on some feature

**Comment by zethra** [comment]
> But again, it would probably be hated on some feature

I don't understand what you mean.

**Comment by arijit79** [comment]
To use the function, you probably have to enable a minus feature while specifying the minus dependency in your application's Cargo.toml

**Comment by arijit79** [comment]
Thanks in advance when you open up the PR

**Comment by arijit79** [comment]
minus 5.0 will be runtime agnostic. Closing this as now it's completely dependent on end applications on how they leverage minus's `async_paging` function
