### ISSUE TITLE
Ability to select and copy paged text

### ISSUE THREAD

**Issue by sergiimk** [arijit79/minus#48]
**Is your feature request related to a problem? Please describe.**
When paging through a file with `more` or viewing `git log` you can mouse-drag over or double-click the text to select and copy it. Text selection currently doesn't work with `minus`, which is quite limiting.

**Describe the solution you'd like**
Text selection should work similarly to other paginators

**Additional context**
Not sure if this a bug or missing feature - got same results under `bash` and `zsh`.

**Comment by arijit79** [comment]
00d744f2fbfe9736d663cc2a731404a83444261e fixes the issue. I will make a patch release by tomorrow. Thanks for opening the issue.
