### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by realtica** [arijit79/minus#59]
Is it possible to add horizontal support?

**Comment by arijit79** [comment]
Currently no. minus already does line wrappings by default, so I don't see a point why we need horizontal scrolling. If you suggest some good reason on why minus should have implement horizontal scrolling, I might start working on it.

**Comment by realtica** [comment]
> Currently no. minus already does line wrappings by default, so I don't see a point why we need horizontal scrolling. If you suggest some good reason on why minus should have implement horizontal scrolling, I might start working on it.

Yes, for example tui apps needs complete line and the line wrapping is not good.
Other kind of apps that also needs horizontal scrolling for example a table viewer or a CSV viewer.

**Comment by arijit79** [comment]
Ok, I understand your use case scenario and I will start working on it when I get some time. I am kinda busy right now fixing bugs, improving docs etc.

Meanwhile if you want to help, you can submit a PR and I will happily accept it. Also if you need help, you can join the Discord server.

**Comment by arijit79** [comment]
I just start working on this in #65. You can track the implementation progress there. If you want to help, I would really appreciate that.
