### ISSUE TITLE
Scrolling is broken on main branch

### ISSUE THREAD

**Issue by jrb0001** [arijit79/minus#86]
**Describe the bug**
Scrolling down shows junk lines. Scrolling back up skips lines.

**To Reproduce**
`cargo run --features="static_output" --example static`

**Expected behavior**
The screen always shows the numbers in the correct sequence.

**Screenshots**
Scrolling downwards:
![grafik](https://user-images.githubusercontent.com/2380263/200398579-d2e6c909-4f78-4206-9416-505ba2c8c894.png)
Scrolling back up:
![grafik](https://user-images.githubusercontent.com/2380263/200398698-ee3dd98d-8f6e-40ec-b72a-6667b9948240.png)

**Desktop:**
- OS: Debian 11 on WSL 1 on win11
- Terminal: IntelliJ and MobaXterm
- Shell: none and bash
- main branch

**Additional context**
The cause is a `dbg!()` in `src/core/display/mod.rs:63`. I will create a PR to remove it.

**Comment by arijit79** [comment]
Thanks for giving you time. I will be waiting for the PR.
