### ISSUE TITLE
unused `Results`

### ISSUE THREAD

**Issue by danieleades** [arijit79/minus#9]
There are quite a few unused `Result`s in this library.

Normally the compiler would complain about this, but they've been assigned to anonymous variables (`let _ = result`). This keeps the compiler happy, but doesn't actually address the issue. These are all functions which can fail, and with this pattern they will fail *silently*, which in my view is even worse than sprinkling `unwraps` everywhere.

I count 22 instances of fallible functions where the error case is not handled

**Comment by arijit79** [comment]
Thanks for the issue. Although #5 probably fixes all those

**Comment by danieleades** [comment]
At this stage that pull request addresses 3 of the 22 instances, but it also adds 3 new ones.

It's a draft of course, I guess we'll see how many remain once it's merged.

**Comment by arijit79** [comment]
I am currently unsure when #5 will be marked as done. So I will just fix it by myself. Thanks again

**Comment by poliorcetics** [comment]
If #5 is merged I'll address them in a follow up PR, but that's out of scope for #5. Better to split it, else the review will be difficult for @arijit79.
